# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.mrpgc_skilltree
archives_base_name=mrpgc-skill-tree-add-on

# Dependencies
fabric_loader_version=0.17.2
fabric_api_version=0.116.0+1.21.1

# Dependencies

tiny_config_version=3.0.0-fabric

trinkets_version=3.10.0
cloth_config_version=15.0.130
player_anim_version=2.0.0-alpha1+1.21
spell_engine_version=1.8.0+1.21.1-fabric
spell_power_version=1.4.0+1.21.1-fabric
ranged_weapon_api_version=2.2.0+1.21.1-fabric
pufferfish_skills_version=0.16.3+1.21
skill_tree_rpgs_version=1.1.0+1.21.1-fabric
more_rpg_library_version = 2.4.1-1.21.1
combat_roll_version = 2.0.5+1.21.1-fabric